### ISSUE TITLE
debugger crashes wen pausing

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#194]
```
VMERR>     dbg: suspend 8
VMERR>     JD_PANIC() at devicescript/value.c:291 in devs_value_typeof
VMERR>               throw ex;
VMERR>               ^
VMERR>     at abort (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:12953:19)
VMERR>     at _abort (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:13289:11)
VMERR>     at hw_panic (wasm://wasm/000c5152:wasm-function[29]:0xe06)
VMERR>     at jd_panic_core (wasm://wasm/000c5152:wasm-function[609]:0x1e70d)
VMERR>     at devs_value_typeof (wasm://wasm/000c5152:wasm-function[369]:0x132f2)
VMERR>     at expand_value (wasm://wasm/000c5152:wasm-function[95]:0x33f2)
VMERR>     at send_values (wasm://wasm/000c5152:wasm-function[91]:0x2d6e)
VMERR>     at devsdbg_handle_packet (wasm://wasm/000c5152:wasm-function[90]:0x255d)
VMERR>     at jd_services_handle_packet (wasm://wasm/000c5152:wasm-function[581]:0x1dbde)
VMERR>     at jd_process_everything_core (wasm://wasm/000c5152:wasm-function[593]:0x1e1af)
VMERR>     at jd_process_everything (wasm://wasm/000c5152:wasm-function[592]:0x1e168)
VMERR>     at jd_em_process (wasm://wasm/000c5152:wasm-function[46]:0xf76)
VMERR>     at Object._jd_em_process (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:13012:31)
VMERR>     at Object.handlePacket (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:12102:21)
VMERR>     at Socket.<anonymous> (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:12160:29)
VMERR>     at Socket.emit (node:events:513:28)
VMERR>     at addChunk (node:internal/streams/readable:324:12)
VMERR>     at readableAddChunk (node:internal/streams/readable:297:9)
VMERR>     at Readable.push (node:internal/streams/readable:234:10)
VMERR>     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by mmoskal** [comment]
will need a better repro for this.
