### ISSUE TITLE
spurious error message on close socket

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#284]
When running observable test suite in debugger,

```

VM> catch error map
VM> tests: 26, pass: 26, error: 0
VM> RESTART requested
V> dbg: suspend 5
dbgserver: connection closed
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:917:11)
    at Socket._write (node:net:929:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at client.send (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:48907:16)
    at /Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:48816:98
    at Array.forEach (<anonymous>)
    at /Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:48816:81
    at JDBus.emit (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:31959:17)
    at JDBus.processFrame (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:41625:10)
    at JDBus.sendFrameAsync (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:41367:10)
    at processPacket (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:48965:9)
    at WebSocket3.<anonymous> (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:48887:11)
    at WebSocket3.emit (node:events:513:28)
    at WebSocket3.dispatchEvent (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:25986:14)
    at WebSocket3._receiveMessage (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:26131:14)
    at Hybi.<anonymous> (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:26027:15)
    at Hybi.emit (node:events:525:35)
    at Hybi.<anonymous> (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:25363:18)
    at pipe (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:24785:27)
    at Pipeline._loop (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:24792:7)
    at Pipeline.processIncomingMessage (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:24762:12)
    at Extensions.processIncomingMessage (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:24895:24)
    at Hybi._emitMessage (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:25354:26)
    at Hybi._emitFrame (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:25326:23)
    at Hybi.parse (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:25107:22)
    at IO.write (/Users/peli/Documents/devicescript/cli/built/devicescript-cli.cjs:23605:20) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
webclient: connected (ws3, 3 clients)
```

**Comment by pelikhan** [comment]
Maybe fixed by https://github.com/microsoft/devicescript/commit/f30cd1e3d2211fd7b9397c5906fbd7edbe3d39c6.
